#!/bin/bash

# Mise à jour et installation des prérequis
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common acl

# Désinstallation des anciennes versions de Docker
sudo apt-get remove -y docker.io docker-compose docker-compose-v2 docker-doc podman-docker containerd runc

# Ajout de la clé GPG officielle de Docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Ajout du dépôt Docker aux sources APT
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Installation de Docker Engine et Docker Compose
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Ajout de l'utilisateur 'florent' au groupe 'docker'
sudo groupadd docker
sudo usermod -aG docker florent

# Installation du paquet 'acl' pour setfacl
sudo apt-get install -y acl

# Application des permissions sur le socket Docker
sudo setfacl -m user:florent:rw /var/run/docker.sock

echo "Installation de Docker et configuration terminées."
